Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 23, in main
    model.build()
  File "/home/grupo03/M5/Code/models/model_builder.py", line 81, in build
    raise ValueError('Unknown model')
ValueError: Unknown model
